services:
  # Frontend Vue.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000/api/v1
        - VITE_API_KEY=pk_master_admin
    container_name: smart-legal-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge